### ISSUE TITLE
Deploy Lucee Config

### ISSUE THREAD

**Issue by timsayshey** [mikesprague/lucee5-heroku#6] opened 2016-09-17 15:57 UTC
Is there a way to deploy to heroku with Lucee settings included? ie, lucee-server.xml and lucee-web.xml.cfm

This is important because everytime I deploy all of my settings are lost and I have to set a password and reconfigure lucee.

Any suggestions?

Thanks!

**Comment by mikesprague** [comment] 2016-09-17 19:55
Heroku has an ephemeral file system so every time you deploy, and/or every time it wakes up from sleeping, it reverts to what's been deployed in the last commit.

The solution is pretty straight forward. You just need to make any desired changes on your local machine and add/commit them to your git repo. Then when you push to Heroku the changes will be included.

Let me know if you have any more questions.

**Closed as completed** 2016-09-17 20:27 UTC
Labels: question

**Comment by timsayshey** [comment] 2016-09-19 17:54
Thanks @mikesprague -- I tried the following:
- I ran foreman then I set all the Lucee server settings I wanted locally.
- Then I followed the rest of the process including committing all of my changes.
- However once it builds all of my server settings have been reset on Heroku or where overwritten/excluded from the build.

Please advise. Thanks!

**Comment by timsayshey** [comment] 2016-09-19 18:11
This appears to be the issue. These files are being excluded from the build via the pom.xml file:
<exclude>**/lucee-server.xml</exclude>
<exclude>**/lucee-web.xml.cfm</exclude>

**Comment by mikesprague** [comment] 2016-09-19 18:47
Thanks for finding that @timsayshey! I'll fix that in this project.

**Comment by mikesprague** [comment] 2016-09-19 20:32
@timsayshey Those exclude lines actually exclude the files in the maven clean process. 

I did some experimenting and it looks like the web context changes are saved correctly but the server context changes aren't. 

On deploy it seems a new server.xml is written every time, even if one already exists.

I'll look into a way to copy an existing server.xml file post-deploy. Since the original is overwritten, it would require manually copying the file to a saved location before deploying. 

I'm not sure there's a going to be an elegant solution for this regarding the server context. Are there any settings you are using that couldn't be set via the web context (/server/admin/web.cfm)?

**Comment by timsayshey** [comment] 2016-09-19 20:36
I am setting server password, datasources, mail and security settings locally. Problem is that everytime I push a change, I have to go set all of that stuff again.

**Comment by mikesprague** [comment] 2016-09-19 20:39
Right, I get that. Can't you do it via the web context and not the server context? If you do it there then it should keep the changes.

**Comment by timsayshey** [comment] 2016-09-19 20:44
Aren't web settings specific to the url? If so, localhost settings would be different than myapp.heroku.com

**Comment by mikesprague** [comment] 2016-09-19 20:46
Nope, just specific to that context. They will still work on a different URL.

In some environments, usually a dedicated server, one might have several websites hosted on one Luceee server. In that case, you set things in the server context that are globally available to each web context. However, the settings you add in each specific web context are only available to that site.

Since on Heroku you'll only be using one site there's no reason not to use the web context for all of your settings.

**Comment by timsayshey** [comment] 2016-09-19 20:58
Just tested adding the settings to the web context and committed the changes. Then I tried to send an email from heroku and I received "no SMTP Server defined." This tells me that the web context settings aren't persisting either.

**Comment by mikesprague** [comment] 2016-09-19 21:03
You want to confirm their existence via the web admin. 

After deploy, go to `https://you-app-name.herokuapp.com/lucee/admin/web.cfm`, log in and check there. 

Make sure you're using the latest version of this repo too. 

I have confirmed that local changes to the web context do deploy correctly.

**Comment by mikesprague** [comment] 2016-09-19 21:05
You can also set all of these via `application.cfc` and remove the need to make them via the admin.

This is probably the recommended way as your settings are truly application specific. 

It's also possible to read in Heroku environment variables this way if you're using add-ons for things like database, mail, cache, etc.

An example of this would be:

``` java
component output="false" {
  variables.objEnvironment = createObject("java", "java.lang.System").getenv();

  this.hostname = variables.objEnvironment.get("MANDRILL_SMTP_HOST");
  this.port = variables.objEnvironment.get("MANDRILL_SMTP_PORT");
  this.mailusername = variables.objEnvironment.get("MANDRILL_USERNAME");
  this.mailpassword = variables.objEnvironment.get("MANDRILL_APIKEY");
...
}
```

**Comment by timsayshey** [comment] 2016-09-19 21:21
Okay, I removed all my hacks from the code and re-tested. It's working now using the web context. Thanks!
